### ISSUE TITLE
make this package the non-sf version of tidytransit

### ISSUE THREAD

**Issue by tbuckl** [r-gtfs/trread#5]
all the same scripts, tests, etc, without the sf dependencies.

**Comment by tbuckl** [comment]
see https://github.com/r-transit/analyze-transit-data-with-r/issues/1 for why.

**Comment by mpadge** [comment]
Yeah, I think this is a good idea. I generally try to avoid direct `sf` dependencies unless absolutely necessary; makes things much more lightweight that way. Another thing to keep in mind is that it's also relatively straightforward to construct `sfc` objects without a direct dependency, which is what [`dodgr`](https://github.com/ATFutures/dodgr) does. (Only `sf` objects really need the direct dependency.)
